/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
/* Header for class aac_ndkopencv_OpencvNativeClass */

using namespace cv;
using namespace std;

#ifndef _Included_aac_ndkopencv_OpencvNativeClass
#define _Included_aac_ndkopencv_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aac_ndkopencv_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img, Mat &gray);

JNIEXPORT jint JNICALL Java_aac_ndkopencv_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     aac_ndkopencv_OpencvNativeClass
 * Method:    faceDetection
 * Signature: (J)V
 */

void detect(Mat& addrRgba);

JNIEXPORT void JNICALL Java_aac_ndkopencv_OpencvNativeClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
